### ISSUE TITLE
Limit naming based on build tooling chosen

### ISSUE THREAD

**Issue by InfoSec812** [pmlopes/slush-vertx#1]
I was testing out the slush generator and did the following:

```
slush vertx
? Project name: (slush-vertx-project) <CR>
? Which build tool: (Use arrow keys)
❯ Apache Maven 
  Gradle 
  NPM <CR>
? Which language: (Use arrow keys)
❯ java 
  groovy 
  ruby 
  kotlin<CR>
```

The generated project wouldn't compile because `slush-vertx-project` is not a valid name in terms of Java packaging. Need to move the tooling selection before the naming and then set up proper bounds checking on the entered name to ensure it is compatible with the build tooling.

**Comment by pmlopes** [comment]
I've done a refactoring to the base code to be more `slush-alike`. This means that it is also more extensible, for example I've added 3 tasks:

* `git-init`
* `project`
* `verticle`

by default when just using slush you will trigger project that depends on `git-init` and `verticle` there is a helper module that avoids asking the same questions over and over, still there is a need to add validations as you reported here.

https://github.com/pmlopes/slush-vertx/pull/2

**Comment by InfoSec812** [comment]
I am already working on the validation and will merge your changes and
continue working the issue.

Thanks,

Deven
