### ISSUE TITLE
Google Testing API breaks code generation 

### ISSUE THREAD

**Issue by bootstraponline** [pmlopes/slush-vertx#12]
### Version

* vert.x core: 3.5.0
* vert.x web: 3.5.0

### Context

Google Testing API breaks vertx-web.

```
 {
            "name": "$.xgafv",
}
```

gets transformed into `$Xgafv: String? ,`

### Do you have a reproducer?

Yes.

* [testing_v1_openapi_3.json#L78](https://github.com/bootstraponline/flank/blob/f520ddd1d710d230c6081bdb2e209d21c2b4d35f/cloud_testing/apis/testing_v1_openapi_3.json#L78)
* [ApiClient.kt#L139](https://github.com/bootstraponline/flank/blob/f520ddd1d710d230c6081bdb2e209d21c2b4d35f/cloud_testing/mock_server_vertx/src/test/kotlin/ftl/ApiClient.kt#L139)

### Steps to reproduce

1. git clone https://github.com/TestArmada/flank.git
2. git checkout cloud_testing
3. cd cloud_testing/mock_server_vertx
4. gradle test

### Extra

* It seems like there's no valid variable name detection logic.

Moved from https://github.com/vert-x3/vertx-web/issues/831

**Comment by slinkydeveloper** [comment]
I'm porting api client code generation to new https://github.com/pmlopes/vertx-starter, can you check if the problem persists? If yes please open an issue, thank you :smile:

**Comment by bootstraponline** [comment]
I ended up manually writing a mock server. I'll close this issue for now since it's no longer an issue for me.
